version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: cargofy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cargofy_db
      MYSQL_USER: cargofy_user
      MYSQL_PASSWORD: cargofy_pass
    ports:
      - "3306:3306"
    volumes:
      - cargofy_mysql_data:/var/lib/mysql

volumes:
  cargofy_mysql_data: